import CoreGraphics
import Foundation

public struct MockPreviewProvider: AIProvider {
    public init() {}

    public func generateImage(prompt: String, size: CGSize) async throws -> GeneratedSourceImage {
        let pixelSize = PixelSize(
            width: max(1, Int(size.width.rounded())),
            height: max(1, Int(size.height.rounded()))
        )

        return GeneratedSourceImage(
            data: try MockSourceProvider.makeGradientPNG(pixelSize: pixelSize),
            prompt: prompt,
            revisedPrompt: prompt,
            sourceURL: nil
        )
    }

    public func extractWords(
        from image: Data,
        countRange: ClosedRange<Int>
    ) async throws -> [VocabularyItem] {
        let requestedCount = min(max(4, countRange.lowerBound), countRange.upperBound)
        return Array(Self.words.prefix(requestedCount))
    }

    public func analyzeImage(_ image: Data, display: DisplayTarget) async throws -> ImageAnalysis {
        let width = Double(display.pixelSize.width)
        let height = Double(display.pixelSize.height)

        return ImageAnalysis(
            summary: "A mock rural wallpaper with sky, fields, and quiet open space.",
            sceneHints: ["rural", "field", "sunset"],
            safeTextRegions: [
                CoreRect(
                    x: width * 0.12,
                    y: height * 0.10,
                    width: width * 0.76,
                    height: height * 0.34
                )
            ],
            subjectRects: [
                CoreRect(
                    x: width * 0.36,
                    y: height * 0.48,
                    width: width * 0.28,
                    height: height * 0.18
                )
            ],
            lowDetailRects: [
                CoreRect(
                    x: width * 0.10,
                    y: height * 0.08,
                    width: width * 0.80,
                    height: height * 0.28
                )
            ],
            horizonLines: [height * 0.52],
            brightnessHotspots: [],
            maskConfidence: 0.82,
            depthHints: ["sky is far", "field is foreground"],
            notes: "Generated by local mock provider."
        )
    }

    public func evaluate(
        renderedImage: Data,
        plan: LayoutPlan,
        words: [VocabularyItem]
    ) async throws -> EvaluationResult {
        EvaluationResult(
            readability: 0.97,
            sceneFit: 0.95,
            depthBelievability: 0.91,
            desktopCalmness: 0.96,
            wordRelevance: 0.98,
            noBadOcclusion: 0.97,
            textCorrectness: words.isEmpty ? 0 : 1,
            notes: "Mock preview evaluation accepted the rendered wallpaper."
        )
    }

    private static let words: [VocabularyItem] = [
        VocabularyItem(
            word: "meadow",
            partOfSpeech: "noun",
            zhDefinition: "草地",
            example: "A quiet meadow stretches beyond the cottage.",
            difficulty: 2,
            sourceReason: "Open field area in the mock wallpaper."
        ),
        VocabularyItem(
            word: "harvest",
            partOfSpeech: "noun",
            zhDefinition: "收获",
            example: "The harvest season colors the field gold.",
            difficulty: 3,
            sourceReason: "Warm farmland colors in the foreground."
        ),
        VocabularyItem(
            word: "horizon",
            partOfSpeech: "noun",
            zhDefinition: "地平线",
            example: "The horizon glows under the evening sky.",
            difficulty: 3,
            sourceReason: "The sky and field meet across the scene."
        ),
        VocabularyItem(
            word: "tranquil",
            partOfSpeech: "adjective",
            zhDefinition: "宁静的",
            example: "The village feels tranquil after sunset.",
            difficulty: 4,
            sourceReason: "The composition is calm enough for a desktop."
        )
    ]
}
